export const productsData = [
    {
      id: 1,
      image: "/img/shop/products-img1.jpg",
      name: "Blue Glass Power",
      oldPrice: "$321",
      newPrice: "$250",
      saleTag: null,
      newTag: null,
    },
    {
      id: 2,
      image: "/img/shop/products-img2.jpg",
      name: "Smart Boy Coder",
      oldPrice: "$210",
      newPrice: "$200",
      saleTag: "Sale!",
      newTag: null,
    },
    {
      id: 3,
      image: "/img/shop/products-img3.jpg",
      name: "Spider Headphone",
      oldPrice: "$210",
      newPrice: "$200",
      saleTag: null,
      newTag: null,
    },
    {
      id: 4,
      image: "/img/shop/products-img4.jpg",
      name: "Beautiful City Snakes",
      oldPrice: null,
      newPrice: "$150",
      saleTag: null,
      newTag: null,
    },
    {
      id: 5,
      image: "/img/shop/products-img5.jpg",
      name: "Baby Dragon",
      oldPrice: null,
      newPrice: "$240",
      saleTag: null,
      newTag: null,
    },
    {
      id: 6,
      image: "/img/shop/products-img6.jpg",
      name: "Daily Shouter",
      oldPrice: "$150",
      newPrice: "$100",
      saleTag: null,
      newTag: "New!",
    },
  ];
  